### ISSUE TITLE
Uzlikt piezīmēm izpildes laiku

### ISSUE THREAD

**Issue by kapsitis** [dacespulgaosina/AwesomeProject#1]
**Add note** poga atver piezīmes rediģēšanas ekrānu (Title, Text, Priority). Pievienot šai formai arī kalendāru (date+time izvēles vadīklu/widget'u), ar ko uzstāda piezīmes izpildes laiku. 
Vajadzētu izmantot esošas RN pakas (uzstādīt jaunas?). Vajadzētu paredzēt iespēju, ka piezīmei izpildes laika nemaz nav - ja tā ir informatīva nevis ToDo-veida piezīme.

**Comment by dacespulgaosina** [comment]
Datuma un laika izvēles elementi ir ielikti pie `AddNoteComponent.tsx` un ieraksta datubāzē
